//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalheTriagem
    {
        public long ID { get; set; }
        public long TriagemID { get; set; }
        public long ProdutoID { get; set; }
        public int QtdDevolvida { get; set; }
        public string Lote { get; set; }
        public decimal PVP { get; set; }
        public long MotivoDevolucaoID { get; set; }
        public long TratamentoID { get; set; }
        public string Descricao { get; set; }
        public System.DateTime Validade { get; set; }
    
        public virtual MotivoDevolucao MotivoDevolucao { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual Tratamento Tratamento { get; set; }
        public virtual Triagem Triagem { get; set; }
    }
}
