//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILI
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoteProduto
    {
        public long ID { get; set; }
        public long ProdutoID { get; set; }
        public string Lote { get; set; }
        public System.DateTime Validade { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public long TratamentoID { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public Nullable<long> ActualizadoPor { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Tratamento Tratamento { get; set; }
        public virtual User User { get; set; }
    }
}
