//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Morada
    {
        public long ID { get; set; }
        public long NIF { get; set; }
        public string Nome { get; set; }
        public long CodPostalID { get; set; }
        public string Morada1 { get; set; }
        public Nullable<int> Telefone { get; set; }
        public string NomeContacto { get; set; }
        public long TipoDevolvedorID { get; set; }
    
        public virtual CodigoPostal CodigoPostal { get; set; }
        public virtual TipoDevolvedor TipoDevolvedor { get; set; }
    }
}
