//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoTriagem
    {
        public long ID { get; set; }
        public long TriagemID { get; set; }
        public long EANCNP { get; set; }
        public int QtdDevolvida { get; set; }
        public string Lote { get; set; }
        public Nullable<decimal> PVP { get; set; }
        public long MotivoDevolucaoID { get; set; }
        public long TratamentoID { get; set; }
        public Nullable<System.DateTime> Validade { get; set; }
        public Nullable<long> TipologiaID { get; set; }
        public string Localizacao { get; set; }
        public string CodSecundario { get; set; }
        public string Observacoes { get; set; }
    
        public virtual MotivoDevolucao MotivoDevolucao { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual Tipologia Tipologia { get; set; }
        public virtual Tratamento Tratamento { get; set; }
        public virtual Triagem Triagem { get; set; }
    }
}
