//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recepcao()
        {
            this.DetalheRecepcao = new HashSet<DetalheRecepcao>();
        }
    
        public long ID { get; set; }
        public string NrRecepcao { get; set; }
        public System.DateTime DataHora { get; set; }
        public System.DateTime DataChegadaArmazem { get; set; }
        public System.TimeSpan HoraChegadaArmazem { get; set; }
        public long EntreguePor { get; set; }
        public string Observacoes { get; set; }
        public int NrVolumesRecepcionados { get; set; }
        public long Colaborador { get; set; }
        public bool DCR { get; set; }
    
        public virtual Morada Morada { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalheRecepcao> DetalheRecepcao { get; set; }
    }
}
