//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcao
    {
        public long ID { get; set; }
        public string NrRecepcao { get; set; }
        public System.DateTime DataHora { get; set; }
        public System.DateTime DataHoraChegadaArmazem { get; set; }
        public long EntreguePor { get; set; }
        public string NrGuiaTransportador { get; set; }
        public int NrVolumesRecepcionados { get; set; }
        public int NrVolumesGuia { get; set; }
        public long Colaborador { get; set; }
    
        public virtual Morada Morada { get; set; }
        public virtual User User { get; set; }
    }
}
